version: '3'

services:
  dts353f_mqtt_bridge:
    build: '.'
    devices:
      - ${DTS353F_USB_DEVICE}
    environment:
      DTS353F_USB_DEVICE: ${DTS353F_USB_DEVICE}
      UPDATE_INTERVAL: '0.5'
      MQTT_BROKER_ADDRESS: ${MQTT_BROKER_ADDRESS:-localhost}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT:-1883}
      MQTT_TOPIC_PREFIX: 'dts353f/{attribute}'
      MQTT_QOS: '0'
      MQTT_RETAIN: 'true'
    restart: unless-stopped
